### ISSUE TITLE
Each entry in the source-spec should be able to handle multiple sources

### ISSUE THREAD

**Issue by brew** [frictionlessdata/pilot-ukds#4]
Currently, each entry is limited to a single source. But Datapackages can contain multiple resources. Instead `source` should be called `sources` and either accept a single string, or a list of strings.

**Comment by brew** [comment]
Changed `source` so it can handle a list:

```yaml
    source:
      - url: ../data/Employee data.sav
        format: spss
      - url: ../data/invalid.csv
        format: csv
```
